jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check out code repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sanitize ref name
        shell: pwsh
        run: |
          $safeRef = $env:GITHUB_REF_NAME -replace '/', '-'
          echo "SAFE_REF=$safeRef" >> $env:GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/rune-mortier/hello-world-nginx:${{ env.SAFE_REF }}
            ghcr.io/rune-mortier/hello-world-nginx:${{ github.sha }}