name: My First Workflow

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check out code repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t hello-world-nginx:${{ github.ref_name }} -t hello-world-nginx:${{ github.sha }} .

      - name: Run Docker container
        run: docker run -d -p 8080:80 hello-world-nginx:${{ github.ref_name }}