name: My First Workflow

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check out code repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: docker login ghcr.io -u rune-mortier -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/rune-mortier/hello-world-nginx:${{ github.ref_name }} -t ghcr.io/rune-mortier/hello-world-nginx:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/rune-mortier/hello-world-nginx:${{ github.ref_name }}
          docker push ghcr.io/rune-mortier/hello-world-nginx:${{ github.sha }}